import React from 'react'

const About = () => {
    return (
        <div>
            <p>About page CODE SPLITING / LAZY LOADING</p>
            <p>About page</p>
            <p>About page</p>
            <p>About page</p>
            <p>About page</p>
            <p>About page</p>
            <p>About page</p>
            <p>About page</p>
            <p>About page</p>
            <p>About page</p>
            <p>About page</p>
            <p>About page</p>
            <p>About page</p>
            <p>About page</p>
            <p>About page</p>
            <p>About page</p>
            <p>About page</p>
            <p>About page</p>
            <p>About page</p>
            <p>About page</p>
            <p>About page</p>
            <p>About page</p>
            <p>About page</p>
            <p>About page</p>
            <p>About page</p>
            <p>About page</p>
            <p>About page</p>
            <p>About page</p>
            <p>About page</p>
            <p>About page</p>
            <p>About page</p>
            <p>About page</p>
            <p>About page</p>
            <p>About page</p>
            <p>About page</p>
            <p>About page</p>
            <p>About page</p>
            <p>About page</p>
            <p>About page</p>
            <p>About page</p>
            <p>About page</p>
            <p>About page</p>
            <p>About page</p>
            <p>About page</p>
            <p>About page</p>
            <p>About page</p>
            <p>About page</p>
            <p>About page</p>
            <p>About page</p>
            <p>About page</p>
            <p>About page</p>
            <p>About page</p>
            <p>About page</p>
            <p>About page</p>
            <p>About page</p>
            <p>About page</p>
            <p>About page</p>
            <p>About page</p>
            <p>About page</p>
            <p>About page</p>
            <p>About page</p>
            <p>About page</p>
            <p>About page</p>
            <p>About page</p>
            <p>About page</p>
            <p>About page</p>
            <p>About page</p>
            <p>About page</p>
            <p>About page</p>
            <p>About page</p>
            <p>About page</p>
            <p>About page</p>
            <p>About page</p>
            <p>About page</p>
            <p>About page</p>
            <p>About page</p>
            <p>About page</p>
            <p>About page</p>
            <p>About page</p>
            <p>About page</p>
            <p>About page</p>
            <p>About page</p>
            <p>About page</p>
            <p>About page</p>
            <p>About page</p>
            <p>About page</p>
            <p>About page</p>
            <p>About page</p>
            <p>About page</p>
            <p>About page</p>
            <p>About page</p>
            <p>About page</p>
            <p>About page</p>
            <p>About page</p>
            <p>About page</p>
            <p>About page</p>
            <p>About page</p>
            <p>About page</p>
            <p>About page</p>
            <p>About page</p>
            <p>About page</p>
            <p>About page</p>
            <p>About page</p>
            <p>About page</p>
            <p>About page</p>
            <p>About page</p>
            <p>About page</p>
            <p>About page</p>
            <p>About page</p>
            <p>About page</p>
            <p>About page</p>
            <p>About page</p>
            <p>About page</p>
            <p>About page</p>
            <p>About page</p>
            <p>About page</p>
            <p>About page</p>
            <p>About page</p>
            <p>About page</p>
            <p>About page</p>
            <p>About page</p>
            <p>About page</p>
            <p>About page</p>
            <p>About page</p>
            <p>About page</p>
            <p>About page</p>
            <p>About page</p>
            <p>About page</p>
            <p>About page</p>
            <p>About page</p>
            <p>About page</p>
            <p>About page</p>
            <p>About page</p>
            <p>About page</p>
            <p>About page</p>
            <p>About page</p>
            <p>About page</p>
            <p>About page</p>
            <p>About page</p>
            <p>About page</p>
            <p>About page</p>
            <p>About page</p>
            <p>About page</p>
            <p>About page</p>
            <p>About page</p>
            <p>About page</p>
            <p>About page</p>
            <p>About page</p>
            <p>About page</p>
            <p>About page</p>
            <p>About page</p>
            <p>About page</p>
            <p>About page</p>
            <p>About page</p>
            <p>About page</p>
            <p>About page</p>
            <p>About page</p>
            <p>About page</p>
            <p>About page</p>
            <p>About page</p>
            <p>About page</p>
            <p>About page</p>
            <p>About page</p>
            <p>About page</p>
            <p>About page</p>
            <p>About page</p>
            <p>About page</p>
            <p>About page</p>
            <p>About page</p>
            <p>About page</p>
            <p>About page</p>
            <p>About page</p>
            <p>About page</p>
            <p>About page</p>
            <p>About page</p>
            <p>About page</p>
            <p>About page</p>
            <p>About page</p>
            <p>About page</p>
            <p>About page</p>
            <p>About page</p>
            <p>About page</p>
            <p>About page</p>
            <p>About page</p>
            <p>About page</p>
            <p>About page</p>
            <p>About page</p>
            <p>About page</p>
            <p>About page</p>
            <p>About page</p>
            <p>About page</p>
            <p>About page</p>
            <p>About page</p>
            <p>About page</p>
            <p>About page</p>
            <p>About page</p>
            <p>About page</p>
            <p>About page</p>
            <p>About page</p>
            <p>About page</p>
            <p>About page</p>
            <p>About page</p>
            <p>About page</p>
            <p>About page</p>
            <p>About page</p>
            <p>About page</p>
            <p>About page</p>
            <p>About page</p>
            <p>About page</p>
            <p>About page</p>
            <p>About page</p>
            <p>About page</p>
            <p>About page</p>
            <p>About page</p>
            <p>About page</p>
            <p>About page</p>
            <p>About page</p>
            <p>About page</p>
            <p>About page</p>
            <p>About page</p>
            <p>About page</p>
            <p>About page</p>
            <p>About page</p>
            <p>About page</p>
            <p>About page</p>

            <p>About page</p>
            <p>About page</p>
            <p>About page</p>
            <p>About page</p>
            <p>About page</p>

        </div>
    )
}

export default About
